Review Emotion Analysis
Recode-Hive/Scrape-ML pull request #136
Opened 2024-05-25 11:36 UTC by pooja8748

## Related Issue
Review Emotion Analysis Using ML #31

## Description
I completed a Review Emotion Analysis project using Machine Learning. The project involved dataset collection, data preprocessing, feature extraction, model training, evaluation, sentiment prediction, and visualization. This initiative contributes to sentiment analysis advancements, with potential applications in customer feedback analysis and social media sentiment monitoring.

![image](https://github.com/Recode-Hive/Scrape-ML/assets/130728514/223caf61-68cc-476e-a143-5c35e8d17616)

![image](https://github.com/Recode-Hive/Scrape-ML/assets/130728514/cbb26c79-bb3d-4114-a8b4-c3b44a77c1ed)

![image](https://github.com/Recode-Hive/Scrape-ML/assets/130728514/559cc90f-3faf-4f85-8e01-e50445afe0e3)

2024-05-27 13:34 UTC, sanjay-kv requested changes
I think you are pushing all text files to repo this will create a also tof issues including LFS. so only 2 or 23 sample files is required and remaing put in a google derive and mention in the documentation.

2024-05-27 17:47 UTC, pooja8748 commented
> I think you are pushing all text files to repo this will create a also tof issues including LFS. so only 2 or 23 sample files is required and remaing put in a google derive and mention in the documentation.

I have removed those unnecessary txt files from the repo as you said and instead added drive link in README file.

2024-06-07 06:03 UTC, pooja8748 commented
I have removed those unnecessary txt files from the repo as you said and instead added drive link in README file.

2024-06-08 04:35 UTC, sanjay-kv approved these changes

2024-06-08 04:35 UTC, merged